"""create_auth_and_knowledge_tables

Revision ID: 414f57fe4649
Revises: 
Create Date: 2025-06-15 11:41:29.836790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414f57fe4649'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父分类ID'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_knowledge_categories_id'), 'knowledge_categories', ['id'], unique=False)
    op.create_table('knowledge_search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_query', sa.String(length=500), nullable=False, comment='搜索关键词'),
    sa.Column('search_type', sa.String(length=20), nullable=True, comment='搜索类型: keyword, semantic, ai'),
    sa.Column('results_count', sa.Integer(), nullable=True, comment='搜索结果数量'),
    sa.Column('user_ip', sa.String(length=45), nullable=True, comment='用户IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('response_time', sa.Integer(), nullable=True, comment='响应时间(毫秒)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='搜索时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_logs_created', 'knowledge_search_logs', ['created_at'], unique=False)
    op.create_index('idx_search_logs_query', 'knowledge_search_logs', ['search_query'], unique=False)
    op.create_index(op.f('ix_knowledge_search_logs_id'), 'knowledge_search_logs', ['id'], unique=False)
    op.create_table('knowledge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='标签颜色(HEX)'),
    sa.Column('description', sa.Text(), nullable=True, comment='标签描述'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_knowledge_tags_id'), 'knowledge_tags', ['id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('keywords', sa.String(length=500), nullable=True, comment='关键词，逗号分隔'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分类ID'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='来源类型: manual, document, web, api'),
    sa.Column('source_file', sa.String(length=255), nullable=True, comment='源文件名'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='源URL'),
    sa.Column('ai_analysis', sa.JSON(), nullable=True, comment='AI分析结果(JSON格式)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI生成的摘要'),
    sa.Column('ai_keywords', sa.String(length=500), nullable=True, comment='AI提取的关键词'),
    sa.Column('confidence_score', sa.Integer(), nullable=True, comment='置信度分数(0-100)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: draft, published, archived'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('is_featured', sa.Boolean(), nullable=True, comment='是否推荐'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='查看次数'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞次数'),
    sa.Column('share_count', sa.Integer(), nullable=True, comment='分享次数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.String(length=100), nullable=True, comment='更新者'),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_items_category', 'knowledge_items', ['category_id'], unique=False)
    op.create_index('idx_knowledge_items_created', 'knowledge_items', ['created_at'], unique=False)
    op.create_index('idx_knowledge_items_keywords', 'knowledge_items', ['keywords'], unique=False)
    op.create_index('idx_knowledge_items_status', 'knowledge_items', ['status'], unique=False)
    op.create_index('idx_knowledge_items_title', 'knowledge_items', ['title'], unique=False)
    op.create_index(op.f('ix_knowledge_items_id'), 'knowledge_items', ['id'], unique=False)
    op.create_table('knowledge_item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.ForeignKeyConstraint(['knowledge_tag_id'], ['knowledge_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_item_tag', 'knowledge_item_tags', ['knowledge_item_id', 'knowledge_tag_id'], unique=True)
    op.create_index(op.f('ix_knowledge_item_tags_id'), 'knowledge_item_tags', ['id'], unique=False)
    op.create_table('knowledge_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_item_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('summary', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('change_description', sa.Text(), nullable=True, comment='变更说明'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_versions_created', 'knowledge_versions', ['created_at'], unique=False)
    op.create_index('idx_versions_item_version', 'knowledge_versions', ['knowledge_item_id', 'version_number'], unique=True)
    op.create_index(op.f('ix_knowledge_versions_id'), 'knowledge_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_versions_id'), table_name='knowledge_versions')
    op.drop_index('idx_versions_item_version', table_name='knowledge_versions')
    op.drop_index('idx_versions_created', table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    op.drop_index(op.f('ix_knowledge_item_tags_id'), table_name='knowledge_item_tags')
    op.drop_index('idx_unique_item_tag', table_name='knowledge_item_tags')
    op.drop_table('knowledge_item_tags')
    op.drop_index(op.f('ix_knowledge_items_id'), table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_title', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_status', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_keywords', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_created', table_name='knowledge_items')
    op.drop_index('idx_knowledge_items_category', table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_knowledge_tags_id'), table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    op.drop_index(op.f('ix_knowledge_search_logs_id'), table_name='knowledge_search_logs')
    op.drop_index('idx_search_logs_query', table_name='knowledge_search_logs')
    op.drop_index('idx_search_logs_created', table_name='knowledge_search_logs')
    op.drop_table('knowledge_search_logs')
    op.drop_index(op.f('ix_knowledge_categories_id'), table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    # ### end Alembic commands ### 