"""add_user_auth_tables

Revision ID: 425ccad1ad52
Revises: 414f57fe4649
Create Date: 2025-06-15 11:42:46.293027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ccad1ad52'
down_revision = '414f57fe4649'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表，JSON格式'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否验证邮箱'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级管理员'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('login_count', sa.Integer(), nullable=True, comment='登录次数'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True, comment='失败登录次数'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='锁定到期时间'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_login_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='登录时间'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('login_method', sa.String(length=20), nullable=True, comment='登录方式'),
    sa.Column('is_success', sa.Boolean(), nullable=True, comment='是否成功'),
    sa.Column('failure_reason', sa.String(length=200), nullable=True, comment='失败原因'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='会话ID'),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True, comment='登出时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_logs_ip', 'user_login_logs', ['ip_address'], unique=False)
    op.create_index('idx_login_logs_time', 'user_login_logs', ['login_time'], unique=False)
    op.create_index('idx_login_logs_user', 'user_login_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_login_logs_id'), 'user_login_logs', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_token', sa.String(length=255), nullable=False, comment='会话令牌'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='刷新令牌'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('idx_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_token', 'user_sessions', ['session_token'], unique=False)
    op.create_index('idx_sessions_user', 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_sessions_user', table_name='user_sessions')
    op.drop_index('idx_sessions_token', table_name='user_sessions')
    op.drop_index('idx_sessions_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_login_logs_id'), table_name='user_login_logs')
    op.drop_index('idx_login_logs_user', table_name='user_login_logs')
    op.drop_index('idx_login_logs_time', table_name='user_login_logs')
    op.drop_index('idx_login_logs_ip', table_name='user_login_logs')
    op.drop_table('user_login_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    # ### end Alembic commands ### 